### ISSUE TITLE
Formalise data structure

### ISSUE THREAD

**Issue by chillenzer** [edbennett/glue_analysis#17]
More details for step 2 and 3 of #11. We agreed on having a `pandas.Dataframe` as underlying data structure with an index of 3 levels: `MC Time`, `Time`, `Internal` wherein `Internal` refers to all other structure like interpolating operator, blocking level, etc. and is implemented in a tuple-like fashion. The columns will be one value column (have/should we settle on a name here?) and one column for channel information intended to facilitate keeping multiple independent channels in the same data structure. The readers are in charge of renaming the read in column names etc.

Please, add amendments to the above as you feel the need for.

Concrete steps:
- [x] Test currently existing behaviour of `CorrelatorEnsemble`
- [x] Amend `CorrelatorEnsemble` to work on the new structure
- [x] Enforce internal consistency and via `@property` getter/setters
- [x] Amend both readers to produce the correct data structures
- [x] Update consistency checks to accept new structure

**Comment by chillenzer** [comment]
Did we agree on whether the indexing columns should be implemented as a `pandas.MultiIndex` or just keep them as value columns?

**Comment by chillenzer** [comment]
We could try [dataenforce](https://github.com/CedricFR/dataenforce) for the last bullet. Looks like a good fit, maybe along the lines of
```python3
@property
def correlators(self):
    ...

@correlators.setter
@validate
def correlators(self, other: Dataset[...]):
    ...
```

**Comment by edbennett** [comment]
(Asking this as a question because it's late so I don't trust my judgement, but I don't want to forget)

Would it be possible to disable this for ensembles that are not `frozen`? This is a key feature of `meson_analysis`, which I don't want to diverge from by too much (even if merging it in is out of scope for now)—being able to build up a set of correlators as they are read in number by number; at various points this may create an inconsistency.

You could also imagine wanting to read in an inconsistent ensemble, and then apply some rule to make it consistent. Storing inconsistent correlators in memory isn't a problem; computing observables on them is.

**Comment by edbennett** [comment]
> Did we agree on whether the indexing columns should be implemented as a pandas.MultiIndex or just keep them as value columns?

I find `MultiIndexes` a pain to work with, but I think in principle what we're trying to do is exactly what they're designed for? (Or are they more hierarchical than we might want?) If we a) abstract away all of the `MultiIndex` stuff so the consumer of the library doesn't need to care about it, and/or b) provide some very nice example code in appropriate places of how to do the things a consumer would need to do with a `MultiIndex` (preferably that demonstrates the fluidity/flexibility/beauty/awesomeness of `MultiIndex`, so the choice to use them looks justified) then it could work.
