### ISSUE TITLE
Symmetric interface

### ISSUE THREAD

**Issue by chillenzer** [edbennett/glue_analysis#7]
And last bikeshedding here (hopefully): Just something to think about, but should the interface be symmetric, i.e., `get_numpy[_corr]` vs. `get_numpy_vev`? I mean, I can see how a class called `CorrelatorEnsemble` lends itself to the assumption that `get_numpy` returns a `numpy` representation of correlators but still that asymmetry might come as a surprise to some.

**Comment by edbennett** [comment]
>  I can see how a class called CorrelatorEnsemble lends itself to the assumption that `get_numpy` returns a `numpy` representation of correlators

While I don't see a point in making them private, the intention is that the downstream consumer of the class shouldn't need to touch the vevs, but they will definitely want to use the correlators (subtracted or otherwise). I don't see a point in them always needing to type `get_numpy_correlators` just to be consistent with the `get_numpy_vevs` that they'll never need to type.

**Comment by chillenzer** [comment]
Okay. It's fine with me. No strong opinion really. Just brought it up because I spotted the asymmetry and wanted it to be a conscious decision.
